### ISSUE TITLE
Division by zero error when analyzing target hit/miss

### ISSUE THREAD

**Issue by elliae01** [elliae01/CS460#8]
If hit or miss data is not available and the testreactionalytics.py is ran this error may occur.  See attached screenshot for error message.
![divzeroerror](https://user-images.githubusercontent.com/21211121/38169762-06cc80f6-3541-11e8-83bb-ce7ad9e14414.PNG)

**Comment by unlimiteddigits** [comment]
added the necessary catch for a perfect shooter
